# Fly.io configuration for n8n DFY Autopilot
app = "n8n-dfy-autopilot-prod"
primary_region = "ord"
kill_signal = "SIGTERM"
kill_timeout = "30s"

[experimental]
  cmd = ["npm", "start"]

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "8080"

# Persistent storage for content files (combined storage)
[[mounts]]
  source = "n8n_content"
  destination = "/app/storage"
  initial_size = "50gb"

# HTTP service configuration
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "30s"
    interval = "15s"
    method = "GET"
    path = "/health"
    port = 8080
    timeout = "10s"
    type = "http"

# Resource allocation for video processing workloads
[vm]
  cpu_kind = "shared"
  cpus = 2
  memory = "4gb"

# Process configuration
[[processes]]
  name = "app"
  entrypoint = ["npm", "start"]

# Machine configuration for auto-scaling
[machine]
  restart_policy = "on-failure"

# Console command support
[console]
  command = "/bin/sh"

# Deploy configuration
[deploy]
  release_command = "npm run migrate:prod"
  strategy = "rolling"